version: '3.9'

services:
  buildenv:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./shared
        target: /build
    working_dir: /build
    entrypoint:
      - make
      - xv6.img
      - fs.img
  
  qemu:
    build:
      context: .
      dockerfile: Dockerfile.qemu
    volumes:
      - type: bind
        source: ./shared
        target: /build
    working_dir: /build
    entrypoint:
      - make
      - qemu-nox
