version: '3.9'

services:
  buildenv:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./shared
        target: /build
    entrypoint:
      - sleep
      - infinity
